disabled_rules:
  - cyclomatic_complexity
  - trailing_whitespace
  - switch_case_alignment #
  - todo
  - identifier_name
  #- line_length
 # - operator_whitespace
  #- force_cast
 # - force_try
  - legacy_hashing
  - attributes
  - closure_end_indentation
  - object_literal
  #- type_name
  - trailing_newline
 # - vertical_whitespace
  - weak_delegate
  - empty_count
  - function_parameter_count


opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message
 # - explicit_self
  #- multiline_argoments
  - vertical_whitespace_between_cases


excluded:
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - punpapi/R.generated.swift
  - punpapi/3rd


 
function_body_length:
  - 100 # warning
  - 400 # error

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 200
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 1000 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1500
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 1 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown, github-actions-logging)

